name: Deploy Sentiment Analysis

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The operating system used for the job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Set Hugging Face API key as an environment variable
      - name: Set Hugging Face API key
        run: echo "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}" >> $GITHUB_ENV  # Inject the secret as an environment variable

      # Step 5: Run the application (Flask app)
      - name: Run Sentiment Analysis
        run: |
          python app.py  # This is where your Flask app is executed
